server:
  port: 2220

spring:
  application:
    name: ribbon-consumer
eureka:
  instance:
    hostname: ribbon-consumer
  client:
    serviceUrl:
      defaultZone: http://peer1:1110/eureka/,http://peer2:1111/eureka/