server:
  port: 1111
spring:
  application:
    name: eureka-server-back
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:1110/eureka/
