server:
  port: 1110
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:1111/eureka/
